//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "dept"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i32,
    pub parent_id: i32,
    pub dept_name: String,
    pub sort: i32,
    pub leader: Option<String>,
    pub phone: Option<String>,
    pub email: Option<String>,
    pub enable: i32,
    pub remark: Option<String>,
    pub address: Option<String>,
    pub create_at: String,
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    ParentId,
    DeptName,
    Sort,
    Leader,
    Phone,
    Email,
    Enable,
    Remark,
    Address,
    CreateAt,
    UpdateAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::ParentId => ColumnType::Integer.def(),
            Self::DeptName => ColumnType::String(StringLen::N(50u32)).def(),
            Self::Sort => ColumnType::Integer.def(),
            Self::Leader => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::Phone => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::Email => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::Enable => ColumnType::Integer.def(),
            Self::Remark => ColumnType::Text.def().null(),
            Self::Address => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::CreateAt => ColumnType::custom("DATETIME").def(),
            Self::UpdateAt => ColumnType::custom("DATETIME").def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
