//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "dict_data"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i32,
    pub data_label: String,
    pub data_value: String,
    pub type_code: String,
    pub is_default: i32,
    pub enable: i32,
    pub remark: Option<String>,
    pub create_at: String,
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    DataLabel,
    DataValue,
    TypeCode,
    IsDefault,
    Enable,
    Remark,
    CreateAt,
    UpdateAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::DataLabel => ColumnType::String(StringLen::N(255u32)).def(),
            Self::DataValue => ColumnType::String(StringLen::N(255u32)).def(),
            Self::TypeCode => ColumnType::String(StringLen::N(255u32)).def(),
            Self::IsDefault => ColumnType::Integer.def(),
            Self::Enable => ColumnType::Integer.def(),
            Self::Remark => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::CreateAt => ColumnType::custom("DATETIME").def(),
            Self::UpdateAt => ColumnType::custom("DATETIME").def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
