//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod dept;
pub mod dict_data;
pub mod dict_type;
pub mod photo;
pub mod power;
pub mod role;
pub mod role_power;
pub mod system_log;
pub mod user;
pub mod user_role;
