//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1
#![allow(unused_imports)]
pub use super::dept::Entity as Dept;
pub use super::dict_data::Entity as DictData;
pub use super::dict_type::Entity as DictType;
pub use super::photo::Entity as Photo;
pub use super::power::Entity as Power;
pub use super::role::Entity as Role;
pub use super::role_power::Entity as RolePower;
pub use super::system_log::Entity as SystemLog;
pub use super::user::Entity as User;
pub use super::user_role::Entity as UserRole;
