//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "system_log"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i32,
    pub method: Option<String>,
    pub uid: Option<i32>,
    pub url: Option<String>,
    pub desc: Option<String>,
    pub ip: Option<String>,
    pub success: Option<i32>,
    pub user_agent: Option<String>,
    pub create_at: String,
    pub log_type: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Method,
    Uid,
    Url,
    Desc,
    Ip,
    Success,
    UserAgent,
    CreateAt,
    LogType,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Method => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::Uid => ColumnType::Integer.def().null(),
            Self::Url => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::Desc => ColumnType::Text.def().null(),
            Self::Ip => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::Success => ColumnType::Integer.def().null(),
            Self::UserAgent => ColumnType::Text.def().null(),
            Self::CreateAt => ColumnType::custom("DATETIME").def(),
            Self::LogType => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
