//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "admin_online"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub session_id: Option<String>,
    pub login_name: Option<String>,
    pub dept_name: Option<String>,
    pub ip_addr: Option<String>,
    pub login_location: Option<String>,
    pub browser: Option<String>,
    pub os: Option<String>,
    pub status: Option<String>,
    pub start_timestamp: Option<i64>,
    pub last_access_time: Option<String>,
    pub expire_time: Option<i32>,
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    SessionId,
    LoginName,
    DeptName,
    IpAddr,
    LoginLocation,
    Browser,
    Os,
    Status,
    StartTimestamp,
    LastAccessTime,
    ExpireTime,
    Id,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::SessionId => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::LoginName => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::DeptName => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::IpAddr => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::LoginLocation => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::Browser => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::Os => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::Status => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::StartTimestamp => ColumnType::BigInteger.def().null(),
            Self::LastAccessTime => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::ExpireTime => ColumnType::Integer.def().null(),
            Self::Id => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
