//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "auth"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i32,
    pub auth_name: Option<String>,
    pub auth_url: Option<String>,
    pub user_id: Option<i32>,
    pub pid: Option<i32>,
    pub sort: Option<i32>,
    pub icon: Option<String>,
    pub is_show: Option<i32>,
    pub status: Option<i32>,
    pub power_type: Option<i32>,
    pub create_id: Option<i32>,
    pub update_id: Option<i32>,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    AuthName,
    AuthUrl,
    UserId,
    Pid,
    Sort,
    Icon,
    IsShow,
    Status,
    PowerType,
    CreateId,
    UpdateId,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::AuthName => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::AuthUrl => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::UserId => ColumnType::Integer.def().null(),
            Self::Pid => ColumnType::Integer.def().null(),
            Self::Sort => ColumnType::Integer.def().null(),
            Self::Icon => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::IsShow => ColumnType::Integer.def().null(),
            Self::Status => ColumnType::Integer.def().null(),
            Self::PowerType => ColumnType::Integer.def().null(),
            Self::CreateId => ColumnType::Integer.def().null(),
            Self::UpdateId => ColumnType::Integer.def().null(),
            Self::CreatedAt => ColumnType::custom("datetime").def().null(),
            Self::UpdatedAt => ColumnType::custom("datetime").def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
