//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "task"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i32,
    pub source_type: Option<i32>,
    pub source_server: Option<i32>,
    pub source_path: Option<String>,
    pub dst_type: Option<i32>,
    pub dst_server: Option<i32>,
    pub dst_path: Option<String>,
    pub exclude_type: Option<String>,
    pub task_file_num: Option<i32>,
    pub create_time: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    SourceType,
    SourceServer,
    SourcePath,
    DstType,
    DstServer,
    DstPath,
    ExcludeType,
    TaskFileNum,
    CreateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::SourceType => ColumnType::Integer.def().null(),
            Self::SourceServer => ColumnType::Integer.def().null(),
            Self::SourcePath => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::DstType => ColumnType::Integer.def().null(),
            Self::DstServer => ColumnType::Integer.def().null(),
            Self::DstPath => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::ExcludeType => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::TaskFileNum => ColumnType::Integer.def().null(),
            Self::CreateTime => ColumnType::custom("datetime").def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
